version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:debian-stable_ocaml-4.06.0
    steps:
      - checkout
      - opam install ounit core sexplib xml-light camlon ppx_inline_test ppx_deriving.show
      - run:
          name: Run tests
          command: jbuilder build @runtest @install
